# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bb < Formula
  desc "Unofficial CLI for Bitbucket Cloud"
  homepage "https://github.com/rbansal42/bitbucket-cli"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rbansal42/bitbucket-cli/releases/download/v0.3.0/bb_0.3.0_darwin_amd64.tar.gz"
      sha256 "a3400fc74d8b8366f1eb847892e22170c021d22616c2fc44814b9183319c84ba"

      def install
        bin.install "bb"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rbansal42/bitbucket-cli/releases/download/v0.3.0/bb_0.3.0_darwin_arm64.tar.gz"
      sha256 "fb2191636ff51f6d2e1a27d48936cf692e7119ad309ceb158b110426f045b68a"

      def install
        bin.install "bb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rbansal42/bitbucket-cli/releases/download/v0.3.0/bb_0.3.0_linux_amd64.tar.gz"
      sha256 "4c29c3953f2fdf25befb2f2cc49385cd92a3b3962eb83a0314cbfee7032f09f7"
      def install
        bin.install "bb"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rbansal42/bitbucket-cli/releases/download/v0.3.0/bb_0.3.0_linux_arm64.tar.gz"
      sha256 "c93f38a1fa10aff29317a54092a87b086d6e1401e41e345065d07765feb95fb1"
      def install
        bin.install "bb"
      end
    end
  end

  test do
    system "#{bin}/bb", "--version"
  end
end
