# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bb < Formula
  desc "Unofficial CLI for Bitbucket Cloud"
  homepage "https://github.com/rbansal42/bitbucket-cli"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/rbansal42/bitbucket-cli/releases/download/v0.2.0/bb_0.2.0_darwin_amd64.tar.gz"
      sha256 "1577454fac9df33a0471c8c3d923cf1b3643180bf782d0f5422c0268058a19e1"

      def install
        bin.install "bb"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/rbansal42/bitbucket-cli/releases/download/v0.2.0/bb_0.2.0_darwin_arm64.tar.gz"
      sha256 "4e03e4fba4836e2e92373f6b8689ff75dd8ffac25950c594f923aa4a74f7348e"

      def install
        bin.install "bb"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/rbansal42/bitbucket-cli/releases/download/v0.2.0/bb_0.2.0_linux_amd64.tar.gz"
      sha256 "1e95c8e784b157b8630d20e611c9f05a0de0e5529e00b6b576042e24af4f6afc"
      def install
        bin.install "bb"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/rbansal42/bitbucket-cli/releases/download/v0.2.0/bb_0.2.0_linux_arm64.tar.gz"
      sha256 "fe7c553dfe843fd63f9b0a0dd9ccf7f3122d94b292cab7610b581733b629988d"
      def install
        bin.install "bb"
      end
    end
  end

  test do
    system "#{bin}/bb", "--version"
  end
end
